#!/bin/bash
set -e

echo "Creating users and databases, $POSTGRES_USER, $POSTGRES_PASSWORD, $DRUID_POSTGRES_USER, $DRUID_POSTGRES_PASSWORD, $SUPERSET_DB_USER, $SUPERSET_DB_PASSWORD"

# Create Druid user and database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DRUID_POSTGRES_USER WITH PASSWORD '$DRUID_POSTGRES_PASSWORD';
    CREATE DATABASE druid;
    GRANT ALL PRIVILEGES ON DATABASE druid TO $DRUID_POSTGRES_USER;
    \c druid
    GRANT USAGE, CREATE ON SCHEMA public TO $DRUID_POSTGRES_USER;
EOSQL

echo "Druid user and database created"

# Create Superset user and database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $SUPERSET_DB_USER WITH PASSWORD '$SUPERSET_DB_PASSWORD';
    CREATE DATABASE superset;
    GRANT ALL PRIVILEGES ON DATABASE superset TO $SUPERSET_DB_USER;
    \c superset
    GRANT USAGE, CREATE ON SCHEMA public TO $SUPERSET_DB_USER;
EOSQL

echo "Superset user and database created"