version: "3.8"

services:
  sdk-service:
    container_name: unisights-sdk
    build:
      context: .
      args:
        INSIGHTS_ENDPOINT: http://127.0.0.1:8000/collect/events
        INSIGHTS_SECRET: insights-secret
        INSIGHTS_SALT: analytics-salt
        INSIGHTS_DEBUG: "true"
    ports:
      - "8080:8080"
    # Remove the volume mount to prevent overwriting dist
    # volumes:
    #   - .:/app
    command: ["serve", "-s", "dist", "-l", "8080", "--cors"]
