{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: unisights-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unisights.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SUPERSET_DB_USER: {{ .Values.secrets.supersetDbUser | quote }}
  SUPERSET_DB_PASSWORD: {{ .Values.secrets.supersetDbPassword | quote }}
  SUPERSET_SECRET_KEY: {{ .Values.secrets.supersetSecretKey | quote }}
  SUPERSET_ADMIN_PASSWORD: {{ .Values.secrets.supersetAdminPassword | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.minioRootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.minioRootPassword | quote }}
{{- end }}
