{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: unisights-production-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentVolumeClaims | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: unisights-production-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1Gi
{{- end }}
